version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: currency_tracker_db
    environment:
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_password
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 