services:
  postgres:
    image: postgres:14
    container_name: currency_tracker_db
    environment:
      POSTGRES_USER: currency_user
      POSTGRES_PASSWORD: currency_password
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_tracker_web
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: currency_user
      DB_PASSWORD: currency_password
      DB_NAME: currency_db
      DB_SSLMODE: disable
    depends_on:
      - postgres
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: currency_tracker_bot
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: currency_user
      DB_PASSWORD: currency_password
      DB_NAME: currency_db
      DB_SSLMODE: disable
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 